# Generated by Django 5.0.6 on 2024-08-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_paciente_nacionalidad_archivoadjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='categoria_id',
        ),
        migrations.DeleteModel(
            name='ArchivoAdjunto',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='PacienteCategoria',
        ),
    ]
