# Generated by Django 5.0.6 on 2024-05-18 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_pais_options_alter_cliente_pais_origen_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='pais_origen_id',
            new_name='pais_origen',
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfil_usuario/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
