# Generated by Django 5.0.6 on 2024-05-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_pais_origen_id_usuario_pais_origen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pais_origen',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nacimiento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
