# Generated by Django 5.0.6 on 2024-08-13 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_paciente_turno_duracion_alter_turno_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.paciente'),
        ),
    ]
