# Generated by Django 5.0.6 on 2024-08-14 02:34

import django.db.models.deletion
from django.db import migrations, models
from datetime import datetime, time, timedelta

def set_default_profesional(apps, schema_editor):
    Profesional = apps.get_model('turnos', 'Profesional')
    Turno = apps.get_model('turnos', 'Turno')
    default_profesional = Profesional.objects.first()  # Obtén un objeto Profesional existente
    if default_profesional:
        Turno.objects.filter(profesional__isnull=True).update(profesional=default_profesional)

class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=datetime.now().date()),  # Fecha actual como valor predeterminado
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(default=time(9, 0)),  # Hora predeterminada (9:00 AM)
        ),
        migrations.AddField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.profesional'),
        ),
        migrations.RunPython(set_default_profesional),
    ]
